name: Build firmware

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  NCS_VERSION: v3.2.0
  ZEPHYR_SDK_VERSION: 0.17.4

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out this repo
        uses: actions/checkout@v4

      - name: Build firmware
        uses: ./.github/actions/build-firmware
        with:
          ncs-version: ${{ env.NCS_VERSION }}
          zephyr-sdk-version: ${{ env.ZEPHYR_SDK_VERSION }}

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xm126_bthome_tank-${{ github.sha }}
          path: |
            app/out/merged.hex
            app/out/dfu_application.zip
            app/out/app/zephyr/xm126_bthome_tank.signed.bin
          if-no-files-found: error
